USE netflix
GO

INSERT INTO Programs(title,lengthInMinutes) VALUES ('A Study in Pink',88);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('The Blind Banker',88);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('The Great Game',88);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('A Scandal in Belgravia',88);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('The Hounds of Baskerville',88);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('The Reichenbach Fall',88);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('The Empty Hearse',88);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('The Sign of Three',88);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('His Last Vow',88);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('The Abominable Bride',89);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Pilot',58);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Cat’s in the Bag…',48);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('…And the Bag’s in the River',48);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Cancer Man',48);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Gray Matter',48);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Crazy Handful of Nothin’',48);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('A No-Rough-Stuff-Type Deal',48);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Seven Thirty-Seven',48);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Grilled',48);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Bit by a Dead Bee',48);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Down',48);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Breakage',48);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Peekaboo',48);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Negro Y Azul',48);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Better Call Saul',48);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('4 Days Out',48);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Over',48);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Mandala',48);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Phoenix',48);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('ABQ',48);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('The Crocodile''s Dilemma',68);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('The Rooster Prince',68);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('A Muddy Road',68);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Eating the Blame',68);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('The Six Ungraspables',68);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Buridan''s Ass',68);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Who Shaves the Barber?',68);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('The Heap',68);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('A Fox, a Rabbit, and a Cabbage',68);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Morton''s Fork',68);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('The Life of Brian',94);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Pulp Fiction',154);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Pruimebloesem',80);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Reservoir Dogs',99);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('The Good, the Bad and the Ugly',161);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Andy Warhol''s Dracula',103);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Waiting for Dutch',68);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Before the Law',68);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('The Myth of Sisyphus',68);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('The Gift of the Magi',68);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Fear and Trembling',68);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Rhinoceros',68);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Did you do this? No, you did it!',68);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Loplop',68);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('The Castle',68);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Palindrome',68);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Ober',97);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('Der Untergang',178);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('De helaasheid der dingen',108);
INSERT INTO Programs(title,lengthInMinutes) VALUES ('A Clockwork Orange',136);